### ISSUE TITLE
db engine type

### ISSUE THREAD

**Issue by vojtechhuser** [maryreginaboland/SeaWAS#1]
the code has these nice parameters:
user <- NULL 
pw <- NULL 
port <- NULL 
server <- "server_name"  #server or host 

consider including the 'dialect' parameter

2.
use 'dialect' variable for all translate commands. current code has sql server dialect target hardcoded.

that means I can not run in on RedShift -  i have to edit the hardcoded code first

**Comment by maryreginaboland** [comment]
Hi @vojtechhuser: Thanks for this catch. I updated the code with the dialect term (in the parameters section) to allow users to easily modify it per need.
